name: Deploy Gin Golang Application

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_IMAGE }} .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_IMAGE }}

      - name: Deploy to VM
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          DOCKER_IMAGE: ${{ secrets.DOCKER_IMAGE }}
          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass

          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem

          ssh -o StrictHostKeyChecking=no -i private_key.pem $SSH_USERNAME@$SSH_HOST << EOF
            sudo docker pull $DOCKER_IMAGE

            # Untuk Cabang 1
            sudo docker stop pos-backend-container || true
            sudo docker rm pos-backend-container || true
            sudo docker run -d \
              --name pos-backend-container \
              --network frontend-connect \
              -e DATABASE_USER=root \
              -e DATABASE_PASSWORD=$DATABASE_PASSWORD \
              -e DATABASE_HOST=$SSH_HOST \
              -e DATABASE_NAME=posdatabase \
              -p 8091:8090 \
              $DOCKER_IMAGE

            # Untuk Cabang 2
            sudo docker stop pos-backend-cabang2-container || true
            sudo docker rm pos-backend-cabang2-container || true
            sudo docker run -d \
              --name pos-backend-cabang2-container \
              --network frontend-connect \
              -e DATABASE_USER=root \
              -e DATABASE_PASSWORD=$DATABASE_PASSWORD \
              -e DATABASE_HOST=$SSH_HOST \
              -e DATABASE_NAME=posdatabase-cabang2 \
              -p 8092:8090 \
              $DOCKER_IMAGE
          EOF
