name: Lint Go Code

on:
  push:
    branches:
      - development

jobs:
  lint:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/heckout@v2
        - uses: actions/setup-go@v2
          with:
            stable: 'false'
            go-version: '1.20'

        - name: lint
          run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.52.2

          golangci-lint run    